#!/usr/bin/python

import os
import json

# Get home dir
home = os.environ.get('HOME')

# Process the file
with open(home + '/.config/tint2/pywal.tint2rc', 'rt') as tint2rc_f:
    tint2rc = tint2rc_f.read() 

# Load pywal's color.json 
with open(home + '/.cache/wal/colors.json') as json_f:
    colors = json.load(json_f)

## Replace the file with actual colors
for key, val in colors['special'].items():
    tint2rc = tint2rc.replace('@' + key, val)
for key, val in colors['colors'].items():
    tint2rc = tint2rc.replace('@' + key, val)

# Save updated to default tint2 config (WILL REPLACE ORIGINAL) 
with open(home + '/.config/tint2/tint2rc', 'wt') as new_f:
    new_f.write(tint2rc)

# Update tint2
os.system("killall -SIGUSR1 tint2")
