#!/usr/bin/sh

source ~/.cache/wal/colors.sh

#################
#     tint2     #
#################

## -- 1. A pywal user template of a tint2 config must be placed on ~/config/wal/templates/colors.tint2rc
## -- 2. Generate a color scheme using pywal
## -- 3. Run this script to update tint2, can be ran with a single command
##        wal -i /path/to/image -o wal-tint2

# Check if tint2rc exists 
if [ -f ~/.cache/wal/colors.tint2rc ]; then
   
   if [ ! -f ~/.config/tint2/tint2rc ]; then
       ln -s ~/.cache/wal/colors.tint2rc ~/.config/tint2/tint2rc
   fi
   
   # Relad tint2 conf
    killall -SIGUSR1 tint2
else 
    echo "Wal hasn't been generated or ~/.config/wal/templates/colors.tint2rc is missing"
fi


#################
#     cava      #
#################

# Check if cava/config is a symbolic link, and colors.cava is generated
if [[ ! -L ~/.config/cava/config && -f ~/.cache/wal/colors.cava ]]; then
    ln -s ~/.cache/wal/colors.cava ~/.config/cava/config
fi

#################
#    oomox      #
#################
oomox-cli ~/.cache/wal/colors-oomox --output pywal-oomox

#################
#   lockscreen  #
#################
resolution=$(xdpyinfo  | grep -oP 'dimensions:\s+\K\S+')
betterlockscreen --update $wallpaper --resolution $resolution
