#! /bin/sh

# Bash functions that only runs the program if not yet running 
# To avoid mulitiple programs running
function run_once {
    program=$1
    restart=$2
    if ! pgrep -x $program > /dev/null; then
        $program &
    elif [ $restart = "restart" ]; then
        pkill $program 
        sleep 1s
        $program &
    fi
}

# Load wallpaper
sh ~/.fehbg &

# Bind super key to super + shift  + space 
# Which is bound to rofi in sxhkd
xcape -e 'Super_L=Super_L|Shift_L|space' &

# Set the cursor
xsetroot -cursor_name left_ptr &

# Fix Java error
wmname LG3D

# Disable touch and pen
sh ~/.screenlayout/mode.sh normal &

# Autostart applications
run_once picom restart
run_once sxhkd
run_once tint2
run_once udiskie
