#! /bin/sh

# Run sxhkd if not yet running
if ! pgrep -x  sxhkd > /dev/null; then
	sxhkd &
fi

# Set number of desktops per monitor
bspc monitor LVDS-1 -d IV V VI
bspc monitor DP-2 -d I II III
bspc config border_width         2

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
gap=20
export gap

bspc config window_gap                  $gap
bspc config top_padding                 $(($gap / 2))
bspc config left_padding                $(($gap / 2))
bspc config right_padding               $(($gap / 2))
bspc config bottom_padding              $(($gap / 2))


# Various settings
bspc config split_ratio                 0.52
bspc config border_width                3
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Merge Xresources
xrdb -merge ~/.cache/wal/colors.Xresources &

# Set the border colors.
bspc config normal_border_color         "$color1"
bspc config active_border_color         "$color2"
bspc config focused_border_color        "$color15"

# Desktop rules
bspc rule -a Gimp state=floating follow=on

# Load screen layout (blocking)
sh ~/.screenlayout/dual.sh

# Load wallpaper
sh ~/.fehbg &

# Set the cursor
xsetroot -cursor_name left_ptr &

# Start tint2
tint2 &
