#! /bin/sh

# Bash functions that only runs the program if not yet running 
# To avoid mulitiple programs running
function run_once {
    program=$1
    if ! pgrep -x $program > /dev/null; then
        $program &
    fi
}

# Load screen layout (blocking)
sh ~/.screenlayout/dual.sh

# Set number of desktops per monitor
bspc monitor DP-2 -n 0 -d               Home Development Others
bspc monitor LVDS-1 -n 1 -d             Media
bspc config border_width                2

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
gap=20
panel=40
export gap

bspc config window_gap                  $gap
bspc config top_padding                 $(($gap / 2))
bspc config left_padding                $(($gap / 2))
bspc config right_padding               $(($gap / 2))
bspc config bottom_padding              $panel


# Various settings
bspc config split_ratio                 0.52
bspc config border_width                1
bspc config borderless_monocle          true
bspc config gapless_monocle             false
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Merge Xresources
xrdb -merge ~/.cache/wal/colors.Xresources &

# Set the border colors.
bspc config normal_border_color         "$color1"
bspc config active_border_color         "$color2"
bspc config focused_border_color        "$color15"

# Desktop rules
bspc rule -a Gimp state=floating follow=on

# Load wallpaper
sh ~/.fehbg &

# Set the cursor
xsetroot -cursor_name left_ptr &

# Autostart applications
run_once picom
run_once sxhkd
run_once tint2
